### PR TITLE
[EN] French traduction for developer instructions and corrections to fr.json UI translation. 

### PR DESCRIPTION
**Pull request by LIARDM**
Hello !
I've been wanting to contribute to the project for a while now, but I'm still a bit new to the Foundry technical stack, so I decided to start with a modest initial contribution.

I've worked on translating the developer instruction files and the system interface translation file into French.

I'm available for any discussion or adjustments regarding this contribution !
I'm a bit new too with open-source project contributions, so don't hesitate to point out my mistakes, I'll try to improve !
And I hope this will help, as I hope to bring more technical contributions henceforward.

Best regards,

### CODE REVIEW

**Comment by Eryx5502** [comment]
Hello there!

Thanks for contributing! Any help is of course welcome. Also, feel free to ask for any help you might need if you want to enrol further, e.g. with Foundry technical details (there are some decent introductions on the web, mainly a wiki and a youtube channel you probably know, ask for them if not).

About the PR, I would only make 2 remarks:
1. It might be useful to merge #163 before this one and include the docs modifications there on the translations here. If we do merge this before, we need update the translation once #163 gets merged.
2. It might be good to update both Spanish and French version of section 4 in `add-new-item.md` to warn about how internal and external `ItemConfis`s can be different (specially with the create/update operations, where one needs to call for different methods on the actor depending on the case).

**Comment by LIARDM** [comment]
Hi ! 

Thanks, I will look after some Youtube Channels for more informations ! But if you have a good ressource, I'm willing to dig in !
I've already had some reading with Foundry wikis or technical channel on Discord Foundry channel too. 
 
For the first point, right ! I'll work on updating my version soon with the translation of your recent work on #163, to be in capacity to merge without conflict after you !

For the second point, I'm less comfortable with this technical concept at the moment, and I don't think I can provide a more detailed or informative update. If it's within your expertise, can I leave it to you to write this brief clarification, which I can then translate and incorporate into my PR ?

**Comment by Eryx5502** [comment]
> For the first point, right ! I'll work on updating my version soon with the translation of your recent work on #163, to be in capacity to merge without conflict after you !

That would be perfect, thanks!

> can I leave it to you to write this brief clarification, which I can then translate and incorporate into my PR ?

Sure! Will do once I finish releasing the newest version supporting v10/v11 :D

> Thanks, I will look after some Youtube Channels for more informations ! But if you have a good ressource, I'm willing to dig in !
> I've already had some reading with Foundry wikis or technical channel on Discord Foundry channel too.

I had in mind these ones:
- https://foundryvtt.wiki/en/development/guides/
- https://foundryvtt.wiki/en/development/guides/SD-tutorial

They're not completely up to date since some important changes where introduced on Foundry v10 and v11, and the links above you are prior to those releases. However, it is still the best instructions I'm aware of. Feel free to ask for help if needed (I'm sahasya on discord). Speaking of which, we do use a Discord channel (It's a subchannel of the Spanish ABF discord server) to coordinate the development so if you feel like contributing more, feel free to ask us to include you!

**Comment by Eryx5502** [comment]
I have already added the comments on `add-new-item.md`, and merged #163, so once you have your translations updated we can merge this PR!

**Comment by LIARDM** [comment]
Hi ! 

Great news ! 😄  

I'm not sure if I done well when synchronizing back with the main but in my last commit it seems my last update is here !
I'll take a double check, docs translation and some fix on FR translation aren't urgent matters.
Best news of the day is the release for V11 and for that you have all my thanks (and I think from my GM too ! 😉 

When I'll be ready to do so, I hope to take one of the recommanded firsts issues but not before introducing myself on the Discord Channel  (my username in the server should be Kaya) !

**Comment by LIARDM** [comment]
Hi ! 

Ok, now I'm satisfied.
Yesterday I surely forgot something pushing my updates. 😶

**Comment by Eryx5502** [comment]
Hey!

I was checking the new changes and spot some very minor things. I left some comments on the code about it.



> Best news of the day is the release for V11 and for that you have all my thanks (and I think from my GM too ! 😉

Glad to hear you're exited about it! So are we all after finally being able to release! 🥳

**Comment by LIARDM** [comment]
Great! I'll work on it tomorrow! 

However, I didn't see any comments in the code. 
Did I miss something?

**Comment by Eryx5502** [comment]
It was me the one missing something this time (to hit the submit review button 😅)

**Comment by LIARDM** [comment]
Hi ! No problem !

I corrected and pushed the correction, but it seem's the commit has outdated the rewiew.
All my bad if it was'nt in the right process. 🙂

**Comment by Eryx5502** [comment]
Perfect! I believe everything should be fine an ready to merge after your last commit!

I actually don't know if there's a way of implementing corrections without outdating the review (it is the first time I use this review thing 😂), but it doesn't matter. We'll merge this soon.

**Review by Eryx5502 — APPROVED** [review]

**Pull request merged**
