### PR TITLE
Migrate to V11

### PR DESCRIPTION
**Pull request by Linkaynn**

### CODE REVIEW

**Comment by Eryx5502** [comment]
I was just looking and realised that on several points in the ActorSheet templates, the field `name` is not updated and still references `data.[...]` (for instance, [here](https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/blob/c12555b418942070029fb09beff116b1838b8247/src/templates/actor/parts/mystic/parts/spheres.hbs#L15). I checked and this makes the sheet failing to update any change introduced on those fields, so we need to correct all of those.

**Comment by Linkaynn** [comment]
Nice, if someone it's available would be great to work on it

**Comment by Eryx5502** [comment]
For some reason, on 741e0b5 the changes of system.json overrode both the changes updating the compendium to the new version and the deletion of the requirements. Those changes need to be undone before merging.

**Comment by Eryx5502** [comment]
> For some reason, on [741e0b5](https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/commit/741e0b5df0632b016725797409128fee20120508) the changes of system.json overrode both the changes updating the compendium to the new version and the deletion of the requirements. Those changes need to be undone before merging.

Solved with https://github.com/AnimaBeyondDevelop/AnimaBeyondFoundry/pull/162/commits/22f9a2118a329616605ec670b2d4b5e1106bd5c9.

**Pull request merged**
